version: '3'
services:
  volia:
    build: .
    ports: 
      - "8866:8866"
    volumes:
      - ./code:/home/src/code
    working_dir: /home/src/code
    command: bash -c "voila MapUI.ipynb"
  jupyterlab:
    build: .
    ports: 
      - "8888:8888"
    volumes:
      - ./code:/home/src/maps
    working_dir: /home/src/maps