version: '3'
services:
  jupyterlab:
    build: .
    ports: 
      - "8888:8888" #jupyterlab
      - "8866:8866" #voila
    volumes:
      - ./code:/home/src/code
    working_dir: /home/src/code
    command: bash -c "voila MapUI.ipynb"